# Generated by Django 4.2.7 on 2023-11-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
