# Generated by Django 4.2.6 on 2023-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_author_options_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.PositiveIntegerField(default=60, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
