# Generated by Django 4.2.6 on 2023-10-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_author_unique_together_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='liked_books',
            field=models.ManyToManyField(to='app.book'),
        ),
    ]
