# Generated by Django 4.2.8 on 2023-12-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=10)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
